[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="user_profile_fields" type="few.common.CustomUserProfile.CustomField[]" --]
[#-- @ftlvariable name="request" type="javax.servlet.http.HttpServletRequest" --]
[#-- @ftlvariable name="messages" type="few.support.Messages" --]
[#-- @ftlvariable name="ajax" type="few.support.Ajax" --]
[#-- @ftlvariable name="loginForm" type="few.common.users.model.LoginForm" --]
[#-- @ftlvariable name="userInfo" type="few.common.users.model.UserInfo" --]

[#function json object][/#function]
[#function new_id][/#function]