[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="model_beans" type="few.common.dispatcher_view.presentation.ViewModelBeans" --]
[#-- @ftlvariable name="actions" type="few.common.dispatcher_view.presentation.ViewActions" --]
[#-- @ftlvariable name="news_store" type="few.common.cms.presentation.NewsStore" --]
[#-- @ftlvariable name="texts_store" type="few.common.cms.presentation.TextsStore" --]
[#-- @ftlvariable name="userList" type="few.common.users.presentation.UserList" --]
[#-- @ftlvariable name="user_profile_fields" type="few.common.users.presentation.UserProfileFields" --]
[#-- @ftlvariable name="user_roles" type="few.common.users.presentation.UserRoles" --]
[#-- @ftlvariable name="user_list" type="few.common.users.presentation.UserList" --]
[#-- @ftlvariable name="user_profile" type="few.common.users.presentation.UserProfile" --]
[#-- @ftlvariable name="request" type="few.support.Request" --]
[#-- @ftlvariable name="ajax" type="few.support.Ajax" --]
[#-- @ftlvariable name="loginForm" type="few.common.users.presentation.LoginForm" --]
[#-- @ftlvariable name="messages" type="few.support.Messages" --]
[#-- @ftlvariable name="userInfo" type="few.common.users.presentation.UserInfo" --]

[#function json userList][/#function]