[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="access_log" type="few.common.audit.model.AccessLog" --]
[#-- @ftlvariable name="activity_log" type="few.common.audit.model.ActivityLog" --]
[#-- @ftlvariable name="model_beans" type="few.common.dispatcher_view.model.ViewModelBeans" --]
[#-- @ftlvariable name="actions" type="few.common.dispatcher_view.model.ViewActions" --]
[#-- @ftlvariable name="news_store" type="few.common.cms.model.NewsStore" --]
[#-- @ftlvariable name="texts_store" type="few.common.cms.model.TextsStore" --]
[#-- @ftlvariable name="userList" type="few.common.users.model.UserList" --]
[#-- @ftlvariable name="user_profile_fields" type="few.common.users.model.UserProfileFields" --]
[#-- @ftlvariable name="user_roles" type="few.common.users.model.UserRoles" --]
[#-- @ftlvariable name="user_list" type="few.common.users.model.UserList" --]
[#-- @ftlvariable name="user_profile" type="few.common.users.model.UserProfile" --]
[#-- @ftlvariable name="request" type="few.support.Request" --]
[#-- @ftlvariable name="ajax" type="few.support.Ajax" --]
[#-- @ftlvariable name="loginForm" type="few.common.users.model.LoginForm" --]
[#-- @ftlvariable name="messages" type="few.support.Messages" --]
[#-- @ftlvariable name="userInfo" type="few.common.users.model.UserInfo" --]

[#function json userList][/#function]